// <auto-generated />
namespace Shwallak.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class required_and_address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(required_and_address));
        
        string IMigrationMetadata.Id
        {
            get { return "202008251008191_required_and_address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
