// <auto-generated />
namespace Shwallak.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class validation_for_comment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validation_for_comment));
        
        string IMigrationMetadata.Id
        {
            get { return "202008231348467_validation_for_comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
