// <auto-generated />
namespace Shwallak.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class required_subscriber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(required_subscriber));
        
        string IMigrationMetadata.Id
        {
            get { return "202008241544107_required_subscriber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
