// <auto-generated />
namespace Shwallak.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class requiredarticle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredarticle));
        
        string IMigrationMetadata.Id
        {
            get { return "202008251258431_required-article"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
